version: "3.8"

services:
  newspaperscraper:
    image: newspaperscraper
    build:
      context: scrapy
      dockerfile: ./Dockerfile
    volumes:
      - ./data:/app/data
  database:
    image: newspaperscraper_database
    container_name: database
    restart: unless-stopped
    build:
      context: psql
      dockerfile: ./Dockerfile
